### ISSUE TITLE
Specify local network

### ISSUE THREAD

**Issue by ampf27** [BroadbentT/ROGUE-AGENT#1]
I was trying on kali 2020.4 and I have run both Install.py and Install_exploits.py but when I run RogueAngent.py I get the error "[!] Warning!!! -  You need to specify your local network interface on line 760 of the rogue-agent.py file ..."

This file doesn't exist, only the RogueAngent.py that I assume to be the same, and on the line of this file thre is no reference to any network interface. I have also tried to do put those values manually on the up.tmp file but I get the same message.

How can this be solved?

Thank you

**Comment by BroadbentT** [comment]
Hi ampf27.

Thanks for contacting me.

Rogue Agent its currently set to run via an HTB openvpn connection on tun0 .

Line 760 is now incorrect due to some updating - it should state line 825 !!!

Just adjust the network parameter to your local interface (line 825) if your not using the HTB openvpn connection.

Thanks for bringing this to my attention, I will update the program later tonight. to reflect this.

Regards Sp00ks7.
